name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Deploy
        run: |
          sudo docker compose up --build -d
        working-directory: /home/prathamm0409/interact/interact-frontend
